name: E2E test
on:   
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Install
          run: npm install
        - name: Test
          continue-on-error: true
          run: |
            npm run test:chrome:headless
            npm run test:firefox:headless
        - uses: actions/upload-artifact@v3
          if: always()
          with:
            name: report
            path: reports/**
            retention-days: 30
        - name: Publish HTML report
          if: ${{github.ref == 'refs/heads/master' && success() || failure() }}
          uses: peaceiris/actions-gh-pages@v3.7.3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_branch: report
            publish_dir: ./reports/report